#pragma once

#include <stdio.h>

#include "kyra/defines/core/types.h"


// Return codes -------------------------------------------- //

typedef enum Filesystem_Result {
    FILESYSTEM_SUCCESS                  					= 0,

	FILESYSTEM_ERROR_REF_OUT_FILE_NULL						= -1,
	FILESYSTEM_ERROR_FILEPATH_NULL							= -2,
	FILESYSTEM_ERROR_FILE_ALREADY_OPEN						= -3,
	FILESYSTEM_ERROR_FILE_NULL								= -4,
	FILESYSTEM_ERROR_FILE_NOT_OPEN							= -5,
	FILESYSTEM_ERROR_LINE_NULL								= -6,
	FILESYSTEM_ERROR_DATA_NULL								= -7,
	FILESYSTEM_ERROR_CAPACITY_ZERO							= -8,
	FILESYSTEM_ERROR_CAPACITY_INSUFFICIENT_TO_EXTRACT		= -9,
	FILESYSTEM_ERROR_INVALID_OPERATION_MODE					= -10,
	FILESYSTEM_ERROR_FAILED_TO_OPEN_FILE					= -11,
	FILESYSTEM_ERROR_FAILED_TO_CLOSE_FILE					= -12,
	FILESYSTEM_ERROR_FAILED_TO_READ_LINE					= -13,
	FILESYSTEM_ERROR_FAILED_TO_READ_ALL						= -14,
	FILESYSTEM_ERROR_FAILED_TO_READ_DATA					= -15,
	FILESYSTEM_ERROR_FAILED_TO_ALLOCATE_BUFFER				= -16,
	FILESYSTEM_ERROR_FAILED_TO_READ_BINARY_DATA				= -17,
	FILESYSTEM_ERROR_FAILED_TO_WRITE_LINE					= -18,
	FILESYSTEM_ERROR_FAILED_TO_FLUSH_FILE					= -19,
	FILESYSTEM_ERROR_FAILED_TO_WRITE_DATA					= -20,
	FILESYSTEM_ERROR_FAILED_TO_WRITE_BINARY_DATA			= -21,
	FILESYSTEM_ERROR_FAILED_TO_SEEK_FILE					= -22,
	FILESYSTEM_ERROR_FAILED_TO_CREATE_DIRECTORY				= -23,
	FILESYSTEM_ERROR_FAILED_TO_REMOVE_DIRECTORY				= -24,
	FILESYSTEM_ERROR_FILE_SIZE_INVALID_TO_READ				= -25,
	FILESYSTEM_ERROR_REF_OUT_READ_BUFFER_NULL				= -26,
	FILESYSTEM_ERROR_REF_OUT_FILENAME_NULL					= -27,
	FILESYSTEM_ERROR_REF_OUT_EXTENSION_NULL					= -28,
	FILESYSTEM_ERROR_REF_OUT_DIRECTORY_NULL					= -29,
	FILESYSTEM_ERROR_NO_EXTENSION_FOUND						= -30,
	FILESYSTEM_ERROR_INVALID_SEEK_POSITION					= -31	
} FilesystemResult;


// Modes -------------------------------------------------- //

typedef enum Filesystem_File_Mode {
    FILESYSTEM_FILE_MODE_TEXT,
    FILESYSTEM_FILE_MODE_BINARY
} FilesystemFileMode;

typedef enum Filesystem_IO_Mode {
	FILESYSTEM_IO_MODE_READ,
	FILESYSTEM_IO_MODE_WRITE,
	FILESYSTEM_IO_MODE_READ_WRITE,
	FILESYSTEM_IO_MODE_APPEND
} FilesystemIOMode;


// File --------------------------------------------------- //

typedef struct Filesystem_File {
	FILE                   *stream;
	FilesystemFileMode      file_mode;
	FilesystemIOMode 		io_mode;
	Bool					active;
} File;



